### /teamcity/publisher : /~rpc/getCurrentUser
GET localhost:4000/api/teamcity/publisher/~rpc/getCurrentUser

### TeamCity hook test

POST localhost:4000/api/v1/teamcity/hooks
Content-Type: application/json

{
  "buildId": 41437,
  "branchName": "feature/RCP-9999-issue-new",
  "projectAliasId": "micro-workspaces",
  "type": "BUILD_COMPLETE"
}

### Commit Publisher - Upsource '/~buildStatus' = FAILURE
POST localhost:4000/api/teamcity/publisher/~buildStatus
Content-Type: application/json

{
  "revisionDate": 1647509577000,
  "name": "/ micro.workspaces / Test Pull Request #51",
  "revisionMessage": " --- 5.txt\n",
  "project": "micro-workspaces",
  "description": "Build started",
  "state": "failed",
  "url": "http:///viewLog.html?buildId=41470&buildTypeId=TestPullRequest",
  "revision": "234e71867f9878792324242315af64cc72d2976d"
}

### Commit Publisher - Upsource '/~buildStatus' = SUCCESS
POST localhost:4000/api/teamcity/publisher/~buildStatus
Content-Type: application/json

{
  "revisionDate": 1647509577000,
  "name": "/ micro.workspaces / Test Pull Request #53",
  "revisionMessage": " --- 5.txt\n",
  "project": "micro-workspaces",
  "description": "Success",
  "state": "success",
  "url": "http:///viewLog.html?buildId=41504&buildTypeId=TestPullRequest",
  "revision": "234e71867f9878792324242315af64cc72d2976d"
}

### Commit Publisher - Upsource '/~buildStatus' = SUCCESS RELATED
POST localhost:4000/api/teamcity/publisher/~buildStatus
Content-Type: application/json

{
  "revisionDate": 1648110333000,
  "name": "ILD / 1. Development / Test / / UI Pull Requests Tests #4",
  "revisionMessage": "Merge branch 'develop' into feature/RCP-1111-adn\n",
  "project": "micro-workspaces",
  "description": "Success",
  "state": "success",
  "url": "http://base/viewLog.html?buildId=41761&buildTypeId=FrontendUnitTest_PullRequestsTests",
  "revision": "50b5f775a546f8a7177121d1ee9669ba99c2573d"
}